calibrated: 1
equilibrium:
    sign: 1
    signFlexor: 1
    signExtensor: -1
    nameFlexor: "shoulder_flexor"
    nameExtensor: "shoulder_extensor"
    servoRange: 12.5664
    servoOffset: 0
signEncoder: 1
signJoint: 1
name: "shoulder_roll"
nameEncoder: "shoulder_roll_encoder"
minAngle: -0.2
maxAngle: 2.4
maxAbsForwardError: 0.3
gains:
    P: 0.01
    I: 0
    D: 0.1
